### ISSUE TITLE
Variable KMS ID needs KMS ARN as input

### ISSUE THREAD

**Issue by ka1h** [Hapag-Lloyd/terraform-aws-bastion-host-ssm#78]
Hi, quick heads up: Your varible `kms_key_id` seems to need the KMS ARN, not the KMS ID. This is kind of misleading, because the variable `kms_key_id` from the TF resource `aws_ami_copy` actually needs the ARN, not the ID, from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_copy#kms_key_id:

"The full ARN of the KMS Key to use when encrypting the snapshots of an image during a copy operation. If not specified, then the default AWS KMS Key will be used".

Had a quick look around: I think your `examples/full/main.tf` and your variable description are affected. Your example should be:

```
- kms_key_id = module.kms_key.key_id
+ kms_key_id = module.kms_key.key_arn
```

Cheers,
Kai

**Comment by kayman-mk** [comment]
Good spot! Thanks for reporting.
